### ISSUE TITLE
ACM Club Resources

### ISSUE THREAD

**Issue by 0dd1tty** [0dd1tty/NCSA-Student-Chapter-CSU-Pueblo#7]
We need to check with Professor Martinez on the status of the ACM club. We may be able to absorb left over funding and assets.

**Comment by 0dd1tty** [comment]
NCSA Exec Board, 

I have already emailed Professor Martinez to setup  a meeting to discuss ACM club status and resources. I've been giving information they had a small amount of left over funding and they may have some assets/resources we can absorb and make ours. Awaiting reply from Professor Martinez.

**Comment by 0dd1tty** [comment]
Meeting with Professor Wayne Martinez on Monday July 24, 2017 at 10:30 AM. Going to cover ACM club left over resources and assets with him. If anyone from the NCSA Executive Board would like to attend please meet at about 10:15 before the meeting.

**Comment by jakevigil** [comment]
Read

**Comment by 0dd1tty** [comment]
No meeting had occurred with Professor Martinez and a phone conversation was conducted since the Professor was not present at meeting time. The final words from Professor Martinez were that left over ACM club resources and funding would not be  transferred over.  Setting issue to the Done column.

**Comment by jakevigil** [comment]
Cool man, no prob with Mr Martinez' decision. We can do it! Maybe later if ACM falls through, he'll reconsider. Ttyl

On Jul 26, 2017, at 21:46, Mario Zamora <notifications@github.com<mailto:notifications@github.com>> wrote:


No meeting had occurred with Professor Martinez and a phone conversation was conducted since the Professor was not present at meeting time. The final words from Professor Martinez were that left over ACM club resources and funding would not be transferred over. Setting issue to the Done column.
